"""initial migration

Revision ID: 7453acc8a3de
Revises: 
Create Date: 2025-11-07 00:02:30.651284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '7453acc8a3de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_name')
    )
    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.create_index('idx_hashtags_tag_name', ['tag_name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=1024), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'PENDING_VERIFICATION', 'SUSPENDED', 'DEACTIVATED_BY_USER', 'DEACTIVATED_BY_ADMIN', name='user_status_enum'), server_default='PENDING_VERIFICATION', nullable=False),
    sa.Column('profile_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('privacy_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email_lower', [sa.literal_column('lower(email)')], unique=True)
        batch_op.create_index('idx_users_username_lower', [sa.literal_column('lower(username)')], unique=True)

    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_index('idx_followers_followed_id', ['followed_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_recipient_is_read', ['recipient_user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_type', sa.Enum('REGULAR', 'RATE_POST', name='post_type_enum'), server_default='REGULAR', nullable=False),
    sa.Column('media_url', sa.String(length=1024), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'FOLLOWERS_ONLY', 'PRIVATE', name='post_visibility_enum'), server_default='PUBLIC', nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reshare_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('content IS NOT NULL OR media_url IS NOT NULL', name='ck_post_content_or_media_required'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_posts_created_at_desc', [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index('idx_posts_location_gist', ['location'], unique=False, postgresql_using='gist', postgresql_where=sa.text('location IS NOT NULL'))
        batch_op.create_index('idx_posts_user_id', ['user_id'], unique=False)

    op.create_table('post_hashtags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'hashtag_id')
    )

    op.create_table('post_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.create_index('idx_post_likes_post_id', ['post_id'], unique=False)

    op.create_table('post_mentions',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    with op.batch_alter_table('post_mentions', schema=None) as batch_op:
        batch_op.create_index('idx_post_mentions_post_id', ['post_id'], unique=False)
        batch_op.create_index('idx_post_mentions_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_mentions', schema=None) as batch_op:
        batch_op.drop_index('idx_post_mentions_user_id')
        batch_op.drop_index('idx_post_mentions_post_id')

    op.drop_table('post_mentions')
    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_index('idx_post_likes_post_id')

    op.drop_table('post_likes')
    with op.batch_alter_table('post_hashtags', schema=None) as batch_op:
        batch_op.drop_index('idx_posthashtags_hashtag_id')

    op.drop_table('post_hashtags')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_posts_user_id')
        batch_op.drop_index('idx_posts_location_gist', postgresql_using='gist', postgresql_where=sa.text('location IS NOT NULL'))
        batch_op.drop_index('idx_posts_location', postgresql_using='gist')
        batch_op.drop_index('idx_posts_created_at_desc')

    op.drop_table('posts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_recipient_is_read')

    op.drop_table('notifications')
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_index('idx_followers_followed_id')

    op.drop_table('followers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_username_lower')
        batch_op.drop_index('idx_users_location', postgresql_using='gist')
        batch_op.drop_index('idx_users_email_lower')

    op.drop_table('users')
    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.drop_index('idx_hashtags_tag_name')

    op.drop_table('hashtags')
    # ### end Alembic commands ###
